<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'blog' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/blog']], [], [], []],
    'create' => [[], ['_controller' => 'App\\Controller\\TestController::create'], [], [['text', '/blog/create']], [], [], []],
    'edit' => [['id'], ['_controller' => 'App\\Controller\\TestController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/blog/edit']], [], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\TestController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/blog/delete']], [], [], []],
    'comment' => [['id'], ['_controller' => 'App\\Controller\\TestController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/blog']], [], [], []],
];
