<?php

namespace ContainerOOZqTXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\TestComponent' autowired service.
     *
     * @return \App\Twig\Components\TestComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/TestComponent.php';

        $container->factories['service_container']['App\\Twig\\Components\\TestComponent'] = function () use ($container) {
            return new \App\Twig\Components\TestComponent();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\TestComponent']();
    }
}
